hw_15(pageobject-steps)
Degandr/Java_cours pull request #15
Opened 2023-12-03 16:45 UTC by Degandr

2023-12-05 06:09 UTC, khadasevich requested changes

2023-12-05 06:09 UTC, khadasevich commented on src/test/java/Home_work_15/PageObject/Pages/LoginPage.java
> +        Selenide.open(StartPageUrl.SITE_URL);
Здесь можно убрать Selenide. и сделать статический импорт метода open

2023-12-05 06:09 UTC, khadasevich commented on src/test/java/Home_work_15/Tests/Autotests/AddBikeLightToCartTest.java
> +        cartPage.checkBikeLightRemoveButton();
Вот здесь лучше использовать методы из шагов, раз есть такой слой, как шаги, но возможно ты просто хотел попробовать писать тесты минуя шаги

2023-12-05 06:09 UTC, khadasevich commented on src/test/java/Home_work_15/Tests/Autotests/PriceSortingTest.java
> +    public void priceSortingPageObject() {
Названия тестовых методов следует заканчивать словом Test, это необхожимо для идентификации тестовых методов Maven'ом

2023-12-07 19:09 UTC, Degandr commented on src/test/java/Home_work_15/Tests/Autotests/PriceSortingTest.java
> +    public void priceSortingPageObject() {
Добавил слово Test в конец каждого тестового метода

2023-12-07 19:11 UTC, Degandr commented on src/test/java/Home_work_15/Tests/Autotests/AddBikeLightToCartTest.java
> +        cartPage.checkBikeLightRemoveButton();
В каждом тестовом классе есть два метода: один через PageObject, второй - через Steps. В данном случае - это чистый (на сколько это возможно) PageObject

2023-12-07 19:11 UTC, Degandr commented on src/test/java/Home_work_15/PageObject/Pages/LoginPage.java
> +        Selenide.open(StartPageUrl.SITE_URL);
Fixed

2023-12-08 06:05 UTC, merged