hw_16(wrappers)
Degandr/Java_cours pull request #16
Opened 2023-12-03 18:10 UTC by Degandr

2023-12-05 06:14 UTC, khadasevich requested changes

2023-12-05 06:14 UTC, khadasevich commented on src/test/java/Home_work_16/Elements/ProductsAddRemoveButtonElement.java
> +            Assert.fail("Can't add to cart because product is already on cart!");
Вот тут assert сыграет плохую службу, он будет фейлить тест, хотя по факту в приложении и не будет бага, да и не стоит делать прямы проверки в самом элементе

2023-12-05 06:14 UTC, khadasevich commented on src/test/java/Home_work_16/ProductsPage.java
> +    public void clickSpecificLink() {
название тестового метода заканчиваем словом Test

2023-12-07 19:14 UTC, Degandr commented on src/test/java/Home_work_16/ProductsPage.java
> +    public void clickSpecificLink() {
fixed

2023-12-07 19:33 UTC, Degandr commented on src/test/java/Home_work_16/Elements/ProductsAddRemoveButtonElement.java
> +            Assert.fail("Can't add to cart because product is already on cart!");
fixed

2023-12-08 06:09 UTC, merged